server:
  port: 8992
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/youngtse?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      # 获取连接的超时时间（毫秒）
      connection-timeout: 30000
      # 连接池中的最小空闲连接数
      minimum-idle: 5
      # 连接池中的最大连接数
      maximum-pool-size: 50
      # 自动提交
      auto-commit: true
      # 连接的最大空闲时间（毫秒）
      idle-timeout: 600000
      #连接的最大存活时间（毫秒）
      max-lifetime: 1800000
      pool-name: MyHikariCP
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 自定义配置
customize:
  # 验证码过期过期时间，单位min
  captchaExpirationTime: 5
  # jwt过期时间，单位min
  jwtExpirationTime: 60
  # 日志路径
  logging:
    path: /tmp/logs
  # 是否开启SpringSecurity权限验证 true开启 false关闭
  security:
    enabled: false
  # 公钥
  public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAudDMI1n24ImU+garF8Le5zoERG576QaxnhLhBt+qeJflZMoXK9nsl6FeEasY7q5ywbUX2/ljcJfWkQTbOwYjsfcabnUkX7UWgDOWARd4cDGxdMMj2Br9YQhBAMKY4J1y6eVpPO54+/oeq9tcVWain5j9f7bTgJRNwk3kwqAWiOgo1wmbpyUu2/KP1pYG0CaQUTIshTtvV+9eLVtYiM61TDScQCAcM8mVNFJzTYaTH/eeLaSQo5x0KFqX6qOdLB9r6J0bh5YDIbm3r+CFwUrAj7lVuWvnLSD7OITfQYVKbcv81ilbVK1YuXoakJneMQfP3ouxalzgGuejDbJb2KTlIwIDAQAB
  # 私钥
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC50MwjWfbgiZT6BqsXwt7nOgREbnvpBrGeEuEG36p4l+Vkyhcr2eyXoV4RqxjurnLBtRfb+WNwl9aRBNs7BiOx9xpudSRftRaAM5YBF3hwMbF0wyPYGv1hCEEAwpjgnXLp5Wk87nj7+h6r21xVZqKfmP1/ttOAlE3CTeTCoBaI6CjXCZunJS7b8o/WlgbQJpBRMiyFO29X714tW1iIzrVMNJxAIBwzyZU0UnNNhpMf954tpJCjnHQoWpfqo50sH2vonRuHlgMhubev4IXBSsCPuVW5a+ctIPs4hN9BhUpty/zWKVtUrVi5ehqQmd4xB8/ei7FqXOAa56MNslvYpOUjAgMBAAECggEBAK87RQghkzv1A1U2bKsfzu3oPJX8S0ZaVa5ox2WgEDdhp6cBHhDwlrn4J6op3H1abkZW7YU5Dpnj1ykzlzt2crsl+Psp5X+MWwfTniaxZ5cGhf9C986YxVJ4YjTBT0KjuPbyregUTGv0WHBhkhXHkJ1JveZvF84uDZartowERLwd86PRcojxVeEOdjbE0gMmZifpQDJKdCtbAdZmKZGOWhzK0/sqOxKtT8N15m/NV9FZqgow2nV/j/ht3eEKhSC9o1M8b2t3N8WahBoFMW2bYvWX2HijZIayq62pX+V8hpe/+1QsJ+3mjlYBPtHVPrE5XSVLXHeSnlw3UxFgjqixx+ECgYEA/+iM+Ato8Qcr9ja0C9Quzf9dGSNd0H/UZfUuKDj7cId8HgaLTlIX6ntJ52DHr32b521gH3p5myi5fVosZDpSlXw/lJ4dCM4xRlnayIGFbODe/fPvsqirLo0BqzMVhra7pYLir3Xz20toXWn31gWg9tizY6aTTMY63oNVBGdm+a0CgYEAueHS84ZhCWpBZG892XucITsnCifQtBPWliDIIzURRPRI819hpeGoxquwWDUZ6wu2FL6qL8FK/K/pHhTUcccO+pJ5UWVpH/utYig0g7Hw5lOqL6xzYsjbuBcrmWTjqTARzY652u7AqcPUYdy8tH0Emm688R49GYYf+LY5Futd1A8CgYEA2nEhU+I5c/TRO9w6GBbI1SJzz692tzFGlrmQ6tipGMct1Vt0sig1LfyLeywLh+tKl2Ovt28OOrmqjCva1LtMHznt8+h7lDadrRWqQZj90ZCqCFCffPupE5VdpUt3xoRY7NEquueOftSBg6ue2Fv5qHwVtKxN9C0Jt0KX4ah6KAkCgYBifYJN4ITn/TH66mpmIvXeMb6ExgXydJR95Y7GAOdOlvVUZtSRlVjdM7lzc2dxQDpREZmRRiTacMbfVoAebS/FmvjHJSmnda4v1UfGA/G1yNzi98gHro+lIjnKxEdQrRSxyw81Ls5M5WNSGyitpZRb05MvWytaq9Oi78KeH0YPBwKBgHDkppU1hdeob3Ix50sUf2lUer0FXejnSEufOaTxNLa106su4XK2vAzzWDNsBAeGgkyKZuj3su3rLiwnfx9ua9JHIkpDwsPUD63nl4mryCvwPfs+gtIKCgx70lzZXAI+yvYvOPFYE4X/7m/EOsZCycVoWuFdcU8YT6rOmOuO0BP7
