server:
  port: 8992
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/youngtse?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      # 获取连接的超时时间（毫秒）
      connection-timeout: 30000
      # 连接池中的最小空闲连接数
      minimum-idle: 5
      # 连接池中的最大连接数
      maximum-pool-size: 50
      # 自动提交
      auto-commit: true
      # 连接的最大空闲时间（毫秒）
      idle-timeout: 600000
      #连接的最大存活时间（毫秒）
      max-lifetime: 1800000
      pool-name: MyHikariCP
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 自定义配置
customize:
  # 验证码过期过期时间，单位min
  captchaExpirationTime: 5
  # jwt过期时间，单位min
  jwtExpirationTime: 60
  # 日志路径
  logging:
    path: /tmp/logs
  # 是否开始SpringSecurity权限验证 true开启 false关闭
  security:
    enabled: false
