server:
  port: 8992
spring:
  master:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/youngtse_mater?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
      username: root
      password: root
      # 获取连接的超时时间（毫秒）
      connectionTimeout: 10000
      # 连接的最大空闲时间（毫秒）
      idleTimeout: 5000
      #连接的最大存活时间（毫秒）
      maxLifetime: 1800000
      poolName: Master-Pool
      #连接池中的最大连接数
      maximumPoolSize: 10
      #连接池中的最小空闲连接数
      minimumIdleL: 2
      connectionTestQuery: SELECT 1
  slave:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/youngtse_slave?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
      username: root
      password: root
      # 获取连接的超时时间（毫秒）
      connectionTimeout: 10000
      # 连接的最大空闲时间（毫秒）
      idleTimeout: 5000
      #连接的最大存活时间（毫秒）
      maxLifetime: 1800000
      poolName: Slave-Pool
      #连接池中的最大连接数
      maximumPoolSize: 10
      #连接池中的最小空闲连接数
      minimumIdleL: 2
      connectionTestQuery: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

# 自定义配置
customize:
  # 验证码过期过期时间，单位min
  captchaExpirationTime: 5
  # jwt过期时间，单位min
  jwtExpirationTime: 60
  # 日志路径
  logging:
    path: /tmp/logs
